[package]
name = "swaptrade-contracts"
version = "0.1.0"

[dependencies]

[workspace]
members = ["."]

[network.testnet]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[network.mainnet]
rpc-url = "https://soroban.stellar.org"
network-passphrase = "Public Global Stellar Network ; September 2015"

[network.local]
rpc-url = "http://localhost:8000/soroban/rpc"
network-passphrase = "Standalone Network ; February 2017"
